// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvnHqvKWSovJaeElqLYSlPirahBTZwRhE',
    appId: '1:24608399396:web:f4f84b7b7c837be9b6f8b1',
    messagingSenderId: '24608399396',
    projectId: 'map-demo-a3416',
    authDomain: 'map-demo-a3416.firebaseapp.com',
    storageBucket: 'map-demo-a3416.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhrePO9ygM7SGpK2YJQ6dReCfctgx-mt4',
    appId: '1:24608399396:android:d6d7cdad694953bbb6f8b1',
    messagingSenderId: '24608399396',
    projectId: 'map-demo-a3416',
    storageBucket: 'map-demo-a3416.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnXz3mOpix0ZDXGt0IKvKYDN5QjHASOtQ',
    appId: '1:24608399396:ios:9ccf51ede295c8a5b6f8b1',
    messagingSenderId: '24608399396',
    projectId: 'map-demo-a3416',
    storageBucket: 'map-demo-a3416.appspot.com',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnXz3mOpix0ZDXGt0IKvKYDN5QjHASOtQ',
    appId: '1:24608399396:ios:c642a794370e26cab6f8b1',
    messagingSenderId: '24608399396',
    projectId: 'map-demo-a3416',
    storageBucket: 'map-demo-a3416.appspot.com',
    iosBundleId: 'com.example.quiz.RunnerTests',
  );
}
